/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EssaiRouteImport } from './routes/essai'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthDashboardProjectsRouteImport } from './routes/_auth.dashboard.projects'
import { Route as AuthDashboardPeopleRouteImport } from './routes/_auth.dashboard.people'
import { Route as AuthDashboardEquipmentsRouteImport } from './routes/_auth.dashboard.equipments'
import { Route as AuthEditorProjectIdTeamsRouteImport } from './routes/_auth.editor.$projectId.teams'
import { Route as AuthEditorProjectIdPlanningRouteImport } from './routes/_auth.editor.$projectId.planning'
import { Route as AuthEditorProjectIdMapRouteImport } from './routes/_auth.editor.$projectId.map'
import { Route as AuthEditorProjectIdAppConnectRouteImport } from './routes/_auth.editor.$projectId.app-connect'
import { Route as AuthEditorProjectIdMapItemIdRouteImport } from './routes/_auth.editor.$projectId.map.$itemId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaiRoute = EssaiRouteImport.update({
  id: '/essai',
  path: '/essai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardProjectsRoute = AuthDashboardProjectsRouteImport.update({
  id: '/dashboard/projects',
  path: '/dashboard/projects',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardPeopleRoute = AuthDashboardPeopleRouteImport.update({
  id: '/dashboard/people',
  path: '/dashboard/people',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardEquipmentsRoute = AuthDashboardEquipmentsRouteImport.update({
  id: '/dashboard/equipments',
  path: '/dashboard/equipments',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEditorProjectIdTeamsRoute =
  AuthEditorProjectIdTeamsRouteImport.update({
    id: '/editor/$projectId/teams',
    path: '/editor/$projectId/teams',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthEditorProjectIdPlanningRoute =
  AuthEditorProjectIdPlanningRouteImport.update({
    id: '/editor/$projectId/planning',
    path: '/editor/$projectId/planning',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthEditorProjectIdMapRoute = AuthEditorProjectIdMapRouteImport.update({
  id: '/editor/$projectId/map',
  path: '/editor/$projectId/map',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEditorProjectIdAppConnectRoute =
  AuthEditorProjectIdAppConnectRouteImport.update({
    id: '/editor/$projectId/app-connect',
    path: '/editor/$projectId/app-connect',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthEditorProjectIdMapItemIdRoute =
  AuthEditorProjectIdMapItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthEditorProjectIdMapRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/essai': typeof EssaiRoute
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/dashboard/equipments': typeof AuthDashboardEquipmentsRoute
  '/dashboard/people': typeof AuthDashboardPeopleRoute
  '/dashboard/projects': typeof AuthDashboardProjectsRoute
  '/editor/$projectId/app-connect': typeof AuthEditorProjectIdAppConnectRoute
  '/editor/$projectId/map': typeof AuthEditorProjectIdMapRouteWithChildren
  '/editor/$projectId/planning': typeof AuthEditorProjectIdPlanningRoute
  '/editor/$projectId/teams': typeof AuthEditorProjectIdTeamsRoute
  '/editor/$projectId/map/$itemId': typeof AuthEditorProjectIdMapItemIdRoute
}
export interface FileRoutesByTo {
  '/essai': typeof EssaiRoute
  '/login': typeof LoginRoute
  '/': typeof AuthIndexRoute
  '/dashboard/equipments': typeof AuthDashboardEquipmentsRoute
  '/dashboard/people': typeof AuthDashboardPeopleRoute
  '/dashboard/projects': typeof AuthDashboardProjectsRoute
  '/editor/$projectId/app-connect': typeof AuthEditorProjectIdAppConnectRoute
  '/editor/$projectId/map': typeof AuthEditorProjectIdMapRouteWithChildren
  '/editor/$projectId/planning': typeof AuthEditorProjectIdPlanningRoute
  '/editor/$projectId/teams': typeof AuthEditorProjectIdTeamsRoute
  '/editor/$projectId/map/$itemId': typeof AuthEditorProjectIdMapItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/essai': typeof EssaiRoute
  '/login': typeof LoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/dashboard/equipments': typeof AuthDashboardEquipmentsRoute
  '/_auth/dashboard/people': typeof AuthDashboardPeopleRoute
  '/_auth/dashboard/projects': typeof AuthDashboardProjectsRoute
  '/_auth/editor/$projectId/app-connect': typeof AuthEditorProjectIdAppConnectRoute
  '/_auth/editor/$projectId/map': typeof AuthEditorProjectIdMapRouteWithChildren
  '/_auth/editor/$projectId/planning': typeof AuthEditorProjectIdPlanningRoute
  '/_auth/editor/$projectId/teams': typeof AuthEditorProjectIdTeamsRoute
  '/_auth/editor/$projectId/map/$itemId': typeof AuthEditorProjectIdMapItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/essai'
    | '/login'
    | '/'
    | '/dashboard/equipments'
    | '/dashboard/people'
    | '/dashboard/projects'
    | '/editor/$projectId/app-connect'
    | '/editor/$projectId/map'
    | '/editor/$projectId/planning'
    | '/editor/$projectId/teams'
    | '/editor/$projectId/map/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/essai'
    | '/login'
    | '/'
    | '/dashboard/equipments'
    | '/dashboard/people'
    | '/dashboard/projects'
    | '/editor/$projectId/app-connect'
    | '/editor/$projectId/map'
    | '/editor/$projectId/planning'
    | '/editor/$projectId/teams'
    | '/editor/$projectId/map/$itemId'
  id:
    | '__root__'
    | '/_auth'
    | '/essai'
    | '/login'
    | '/_auth/'
    | '/_auth/dashboard/equipments'
    | '/_auth/dashboard/people'
    | '/_auth/dashboard/projects'
    | '/_auth/editor/$projectId/app-connect'
    | '/_auth/editor/$projectId/map'
    | '/_auth/editor/$projectId/planning'
    | '/_auth/editor/$projectId/teams'
    | '/_auth/editor/$projectId/map/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  EssaiRoute: typeof EssaiRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essai': {
      id: '/essai'
      path: '/essai'
      fullPath: '/essai'
      preLoaderRoute: typeof EssaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/projects': {
      id: '/_auth/dashboard/projects'
      path: '/dashboard/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof AuthDashboardProjectsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/people': {
      id: '/_auth/dashboard/people'
      path: '/dashboard/people'
      fullPath: '/dashboard/people'
      preLoaderRoute: typeof AuthDashboardPeopleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/equipments': {
      id: '/_auth/dashboard/equipments'
      path: '/dashboard/equipments'
      fullPath: '/dashboard/equipments'
      preLoaderRoute: typeof AuthDashboardEquipmentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/editor/$projectId/teams': {
      id: '/_auth/editor/$projectId/teams'
      path: '/editor/$projectId/teams'
      fullPath: '/editor/$projectId/teams'
      preLoaderRoute: typeof AuthEditorProjectIdTeamsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/editor/$projectId/planning': {
      id: '/_auth/editor/$projectId/planning'
      path: '/editor/$projectId/planning'
      fullPath: '/editor/$projectId/planning'
      preLoaderRoute: typeof AuthEditorProjectIdPlanningRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/editor/$projectId/map': {
      id: '/_auth/editor/$projectId/map'
      path: '/editor/$projectId/map'
      fullPath: '/editor/$projectId/map'
      preLoaderRoute: typeof AuthEditorProjectIdMapRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/editor/$projectId/app-connect': {
      id: '/_auth/editor/$projectId/app-connect'
      path: '/editor/$projectId/app-connect'
      fullPath: '/editor/$projectId/app-connect'
      preLoaderRoute: typeof AuthEditorProjectIdAppConnectRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/editor/$projectId/map/$itemId': {
      id: '/_auth/editor/$projectId/map/$itemId'
      path: '/$itemId'
      fullPath: '/editor/$projectId/map/$itemId'
      preLoaderRoute: typeof AuthEditorProjectIdMapItemIdRouteImport
      parentRoute: typeof AuthEditorProjectIdMapRoute
    }
  }
}

interface AuthEditorProjectIdMapRouteChildren {
  AuthEditorProjectIdMapItemIdRoute: typeof AuthEditorProjectIdMapItemIdRoute
}

const AuthEditorProjectIdMapRouteChildren: AuthEditorProjectIdMapRouteChildren =
  {
    AuthEditorProjectIdMapItemIdRoute: AuthEditorProjectIdMapItemIdRoute,
  }

const AuthEditorProjectIdMapRouteWithChildren =
  AuthEditorProjectIdMapRoute._addFileChildren(
    AuthEditorProjectIdMapRouteChildren,
  )

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthDashboardEquipmentsRoute: typeof AuthDashboardEquipmentsRoute
  AuthDashboardPeopleRoute: typeof AuthDashboardPeopleRoute
  AuthDashboardProjectsRoute: typeof AuthDashboardProjectsRoute
  AuthEditorProjectIdAppConnectRoute: typeof AuthEditorProjectIdAppConnectRoute
  AuthEditorProjectIdMapRoute: typeof AuthEditorProjectIdMapRouteWithChildren
  AuthEditorProjectIdPlanningRoute: typeof AuthEditorProjectIdPlanningRoute
  AuthEditorProjectIdTeamsRoute: typeof AuthEditorProjectIdTeamsRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthDashboardEquipmentsRoute: AuthDashboardEquipmentsRoute,
  AuthDashboardPeopleRoute: AuthDashboardPeopleRoute,
  AuthDashboardProjectsRoute: AuthDashboardProjectsRoute,
  AuthEditorProjectIdAppConnectRoute: AuthEditorProjectIdAppConnectRoute,
  AuthEditorProjectIdMapRoute: AuthEditorProjectIdMapRouteWithChildren,
  AuthEditorProjectIdPlanningRoute: AuthEditorProjectIdPlanningRoute,
  AuthEditorProjectIdTeamsRoute: AuthEditorProjectIdTeamsRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  EssaiRoute: EssaiRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
